[build]
	base = "./"
	publish = "dist"
	command = "npm run build"
		
[[headers]]
	for = "/*"
	[headers.values]
		X-Frame-Options = "DENY"
		X-Content-Type-Options = "nosniff"
		X-XSS-Protection = "1; mode=block"
		Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.codepen.io codepen.io *.twitter.com; font-src 'self' 'unsafe-inline' gstatic.com *.gstatic.com; style-src 'self' 'unsafe-inline' googleapis.com *.googleapis.com; media-src 'self' https://www.bluleadz.com; img-src 'self' *.twitter.com data:; frame-src 'self' *.codepen.io *.twitter.com codepen.io; connect-src 'self' *.googleapis.com data:;"

[[headers]]
	for = "/manifest.webmanifest"
	[headers.values]
		Content-Type = "application/manifest+json"

[[headers]]
	for = "/assets/*"
	[headers.values]
		cache-control = "max-age=31536000, immutable"

[[redirects]]
	from = "/hire-me"
	to = "/contact"
	
[[redirects]]	
	from = "/how-to-use-excels-vlookup-to-quickly-update-product-data"
	to = "/blog/how-to-use-excels-vlookup-to-quickly-update-product-data"
	
[[redirects]]	
	from = "/pros-cons-using-wordpress-page-builders/basic-vs-complex-layout"
	to = "/blog/pros-cons-using-wordpress-page-builders/basic-vs-complex-layout"
	
[[redirects]]	
	from = "/progressive-image-loading-with-hubspot"
	to = "/blog/progressive-image-loading-with-hubspot"
	
[[redirects]]	
	from = "/lazy-loading-images-on-hubspot"
	to = "/blog/lazy-loading-images-on-hubspot"
	
[[redirects]]	
	from = "/hubspot-blog-search"
	to = "/blog/hubspot-blog-search"
	
[[redirects]]	
	from = "/rss"
	to = "/rss.xml"

[[redirects]]	
	from = "/feed"
	to = "/rss.xml"